### ISSUE TITLE
How to use motion chaining? - v1.2.0

### ISSUE THREAD

**Issue by CameronDMcLean1** [2775Josh/JAR-Template#14]
Have been using JAR template for a whille, but I just downloaded v1.2.0 because of the ability to have motion chaining. It says that this can be done with a minspeed parameter, but I can not find this anywhere and it is not in any documentation. Any help would be good.

**Comment by 2775Josh** [comment]
Nice catch! Thanks for pointing that out. The minspeed parameter is in the function prototypes of v1.2.0 (check drive.h) and you can pass it that way. I'll update the docs when I get a chance.

**Comment by 2775Josh** [comment]
My fault, it is called "drive_min_voltage" in JAR template.

**Comment by CameronDMcLean1** [comment]
Thank you so much.
